### ISSUE TITLE
32-bit sevenzip install will fail due to downloading exe instead of msi installer

### ISSUE THREAD

**Issue by spoorcc** [boxcutter/windows#127]
Commit 07ca947a updated seven zip url to new version, but for the 32-bit URLs the original `.msi` installer was replaced for the `.exe` installer. Since installation is done with `msiexec` call this will fail, since it is not a msi isntaller anymore.

```
    virtualbox-iso: 2017-08-14 04:59:05 URL:http://www.7-zip.org/a/7z1604.exe [1110564/1110564] -> "C:/Users/vagrant/AppData/Local/Temp/sevenzip/7z1604.exe" [1]
    virtualbox-iso: T h i s   i n s t a l l a t i o n   p a c k a g e   c o u l d   n o t   b e   o p e n e d .     C o n t a c t   t h e   a p p l i c a t i o n   v e n d o r   t o   v e r i f y   t h a t   t h i s   i s   a   v a l i d   W i n d o w s   I n s t a l l e r   p a c k a g e .
    virtualbox-iso:  ==> WARNING: Error 1620 was returned by: msiexec /qb /i "C:\Users\vagrant\AppData\Local\Temp\sevenzip\7z1604.exe"
    virtualbox-iso: ==> ERROR: Directory not found: "C:\Program Files\7-Zip"
    virtualbox-iso:
```
